// Single-source the SDK version: read packages/sdk/package.json and emit
// src/version.ts. Runs before tsc (build + typecheck) so SDK_VERSION always
// matches the published package version. rootDir:src forbids importing
// ../package.json directly, hence this generator. The output is gitignored.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const dir = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(dir, '..', 'package.json'), 'utf8'));
const out = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit. Source: package.json\nexport const SDK_VERSION = ${JSON.stringify(pkg.version)};\n`;
writeFileSync(join(dir, '..', 'src', 'version.ts'), out);
